AY2324S2-CS2113-W14-3/tp

- src/main/java/seedu/duke/parser/Parser.java
> Create Parser skeleton code

- src/test/java/seedu/duke/command/CommandTest.java
> add JUnitTest

- src/main/java/seedu/duke/parser/Parser.java
Added functionality 
1. Check and match user input to command patterns
2. Extract out command arguments
To be further modified to work with Command Class
> Update Parser to be ready for use with Command Class

- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/command/ByeCommand.java
- src/main/java/seedu/duke/parser/Parser.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
- **Continuous Command Processing Loop**: Refactored the application to establish a continuous command processing loop. This loop efficiently listens for, interprets, and executes user commands in real-time.
- **Optimized Scanner Usage**: Refactored the application to use a single `Scanner` instance for reading user inputs, reducing unnecessary resource allocation.
- **Graceful Shutdown**: Introduced a mechanism for gracefully exiting the command loop and the application, improving user control.
> Implement continuous command processing loop with error handling

- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/command/InitCommand.java
- src/main/java/seedu/duke/parser/Parser.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
This pull request introduces the initial skeleton functionality for the **init** command. It lays the groundwork for future enhancements and personalization features within our application.
- **Added `InitCommand.java`**: Establishes the base structure for initializing the user's name.
- **Modified `Parser.java`**: Integrates the `init` command functionality, allowing for its recognition and processing within the application's command parsing flow.
The addition of the `init` command not only allows for setting the user's name but also opens the door for further personalized features in upcoming milestones. It's an essential component for building a more engaging and user-centric application experience.
> Implement Initial Skeleton for 'init' Command

- build.gradle
- src/main/java/seedu/duke/FAP.java
This pull request introduces enhanced error handling and debugging capabilities into the main function of the FAP application. Key changes include:
- Assertions to ensure `moduleList` is properly initialized, preventing null pointer exceptions during application startup.
- Logging for both user inputs and any arising exceptions, facilitating easier troubleshooting and monitoring of the application's behavior.
> Enhance Stability and Debugging in Main Function

- src/main/java/seedu/duke/command/Command.java
- src/main/java/seedu/duke/command/ViewCommand.java
Add assertions and logging for `ViewCommand` class
- **Modified `Command.java`**:
- Add a private attribute logger for subclasses to inherit from and use logging
- **Modified `ViewCommand.java`**:
- Add assertion and logging to check that mode attribute is present for class instance
> Add assertions and logging for ViewCommand Class

- src/main/java/seedu/duke/Exceptions/ModuleException.java
- src/main/java/seedu/duke/command/AddCommand.java
- src/main/java/seedu/duke/command/ByeCommand.java
- src/main/java/seedu/duke/exceptions/ModuleException.java
- src/main/java/seedu/duke/modules/Module.java
- src/main/java/seedu/duke/modules/ModuleList.java
- Introduced `ModuleException` to handle module-specific exceptions, improving error specificity and clarity.
- Integrated assertions in module constructors to ensure non-null, non-empty, and valid inputs for module code, modular credits (MC), and module date, enhancing input validation.
- Implemented custom error handling in `AddCommand` and `ByeCommand` classes to catch and process `ModuleException` and other exceptions, improving application robustness.
- Added regex validation for module grades to ensure they conform to expected patterns (e.g., "A+", "A", "B+", etc.), enhancing data integrity.
- Corrected improper handling of invalid module grades by throwing `IllegalStateException` for unrecognized grades, ensuring consistent handling of module grade states.
- Fixed potential issue …
> Exception handling for Module and ModuleList Class

- src/main/java/seedu/duke/command/RemoveCommand.java
- src/main/java/seedu/duke/exceptions/ModuleNotFoundException.java
- src/main/java/seedu/duke/modules/ModuleList.java
- Added `ModuleNotFoundException`, used in `ModuleList.java` 
- Add assertion statements to eliminate the case of a null variable
> Add Exception Handling and Assertion Statements 

- src/test/java/seedu/duke/parser/ParserTest.java
Added a few test code to test Parser Class
> Add some parser test code

- src/test/java/seedu/duke/FAPTest.java
- Implemented tests in FAPTest to validate the initialization process with both valid and invalid user input
- Tested the system's response to incomplete commands to ensure error messages are displayed as expected
- Utilized ByteArrayInputStream and ByteArrayOutputStream to simulate user input and capture system output for assertions
> Add unit tests for FAP initialization and error handling

- .gitignore
- data/moduleList.txt
- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/modules/Module.java
- src/main/java/seedu/duke/modules/ModuleList.java
- src/main/java/seedu/duke/parser/CommandMetadata.java
- src/main/java/seedu/duke/storage/Storage.java
This pull request introduces a new storage package along with a `Storage` class dedicated to managing the persistence of module information. The implementation aims to streamline the process of saving and loading module data, ensuring robust data integrity and facilitating easy access to module details across application sessions.
- **Module Data Saving and Loading:** Implements methods to serialize module objects to a file and deserialize them back into application state, enabling persistent storage of module information.
- **Directory and File Management:** Adds utility methods to check for and create necessary directories and files, ensuring a seamless storage experience without manual file management.
- Added `moduleList.txt` to `.gitignore` to exclude temporary or local module data …
> Implement Storage Package for Module Data Persistence

- .gitignore
- src/main/java/seedu/duke/storage/Storage.java
- Corrected the method call from `setModuleStatus` to `setModuleTaken` within the `Storage` class to align with the existing method name in the `Module` class, fixing a compilation issue
- Modified `.gitignore` to exclude `moduleList.txt` from version control, preventing accidental inclusion of local module data in future commits
> Update method reference and modify .gitignore

- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/command/InitCommand.java
- src/main/java/seedu/duke/command/ViewCommand.java
- src/main/java/seedu/duke/exceptions/UserException.java
- src/main/java/seedu/duke/modules/Module.java
- src/main/java/seedu/duke/modules/ModuleList.java
- src/main/java/seedu/duke/parser/CommandMetadata.java
- src/main/java/seedu/duke/parser/InitCommandMetadata.java
- src/main/java/seedu/duke/ui/Ui.java
- src/main/java/seedu/duke/user/User.java
- src/test/java/seedu/duke/FAPTest.java
- src/test/java/seedu/duke/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
This pull request includes several changes to improve the functionality and maintainability of the FAP (Future Academic Planner) application. Here's a summary of the changes:
1. **Added UserException class**: A new `UserException` class has been added to handle exceptions related to user inputs and operations.
2. **Updated FAP class**:
- Added a method `resetModuleStatuses(int currSem)` to the `User` class to reset module statuses based on the current semester.
- Modified the `runApplication()` method in the `FAP` class to reset module statuses before processing user input.
3. **Updated InitCommand class**:
- Added parameters `currentSem` and `graduationSem` to the `InitCommand` constructor.
- Updated the `execute` method to set user information including current and graduation semesters. …
> Add and Integrate User class into FAP

- docs/UserGuide.md
> Update UserGuide with add command

- src/main/java/seedu/duke/ui/Ui.java
- Replaced non ASCII characters with "-" so that it appears nicely on terminals
- Capitalized "Study Plan" in "CEG study plan"
> Visual bug fix ViewCommand

- src/main/java/seedu/duke/parser/CommandMetadata.java
> Remove unecessary comments from CommandMetadata

- src/main/java/seedu/duke/command/AddCommand.java
- src/main/java/seedu/duke/modules/ModuleList.java
- Changed `containsModule` to `containsCEGModule`
- Changed `modules.containsCEGModule(moduleCode)` to `modules.getModule(moduleCode)`.
> Fix add module out of CEGModules

- docs/UserGuide.md
- src/main/java/seedu/duke/modules/Module.java
- src/main/java/seedu/duke/modules/ModuleList.java
- src/main/java/seedu/duke/parser/CommandMetadata.java
- src/main/java/seedu/duke/storage/Storage.java
> Remove "CU" grade functionality

- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/storage/Storage.java
> Refactor FAP and Storage to improve code quality

- src/main/java/seedu/duke/modules/ModuleList.java
- Added catch block to handle `IllegalArgumentException` from `CEGModules.mapStringToEnum()` for modules that exist in your taken list, but does not exist in `CEGModules`.
> Fix broken graduate command

- docs/UserGuide.md
- docs/team/jensonjenkins.md
- docs/team/johndoe.md
- src/test/java/seedu/duke/command/ViewGraduateCommandTest.java
In addition to the title, added JUnit tests for the `graduate` command.
> Update user guide for view specific modules

- src/main/java/seedu/duke/ui/Ui.java
add dividers & associate y1-y4 with [Sem 1] to [Sem 8]. 
Addresses #140, #128
> Improve visual formatting of view command

- src/main/java/seedu/duke/storage/Storage.java
This pull request fixes issue #113.
> Address database read bug in Storage class

- src/main/java/seedu/duke/FAP.java
- src/main/java/seedu/duke/storage/Storage.java
As described, for developers to better understand public methods.
> Add JavaDocs for Storage and FAP Class

- docs/team/dextboy.md
> Add skeleton for PPP

- docs/UserGuide.md
- src/main/java/seedu/duke/ui/Ui.java
- text-ui-test/EXPECTED.TXT
Addresses #141 
Updated `Ui.java` and User Guide to reflect changes
> Add more Help Command info

- docs/team/sxfoo.md
Add own PPP to fufill week 12 requirements
> Add PPP `sxfoo.md`

- docs/DeveloperGuide.md
- docs/team/jensonjenkins.md
As described, except for desired GPA and storage sections.
> Instructions for Manual Testing in DG

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/duke/command/DesiredGpaCommand.java
- src/main/java/seedu/duke/command/GradeCommand.java
- src/main/java/seedu/duke/command/ViewGpaCommand.java
- src/main/java/seedu/duke/modules/ModuleList.java
Minor amendments to UG
Added manual instruction to test desiredGPA for DG
Minor bug fix for desiredGPA
> Deliverables update 

- docs/team/dextboy.md
> Include contributions to PPP

- docs/team/dextboy.md
> Include proper formatting for PPP
